[2022-05-12 07:16:33,587] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_consumer_twitter_data manual__2022-05-12T07:16:33.183417+00:00 [queued]>
[2022-05-12 07:16:33,596] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_consumer_twitter_data manual__2022-05-12T07:16:33.183417+00:00 [queued]>
[2022-05-12 07:16:33,597] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:16:33,597] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 07:16:33,598] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:16:33,607] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stop_consumer_twitter_data> on 2022-05-12 07:16:33.183417+00:00
[2022-05-12 07:16:33,612] {standard_task_runner.py:52} INFO - Started process 1475 to run task
[2022-05-12 07:16:33,615] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stop_live_stream_Dag', 'stop_consumer_twitter_data', 'manual__2022-05-12T07:16:33.183417+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/stop_live_stream_dags.py', '--cfg-path', '/tmp/tmpusyf35d_', '--error-file', '/tmp/tmp_lb5smac']
[2022-05-12 07:16:33,617] {standard_task_runner.py:80} INFO - Job 7: Subtask stop_consumer_twitter_data
[2022-05-12 07:16:33,667] {task_command.py:369} INFO - Running <TaskInstance: stop_live_stream_Dag.stop_consumer_twitter_data manual__2022-05-12T07:16:33.183417+00:00 [running]> on host 176cd38f3c0c
[2022-05-12 07:16:33,829] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=stop_live_stream_Dag
AIRFLOW_CTX_TASK_ID=stop_consumer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T07:16:33.183417+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T07:16:33.183417+00:00
[2022-05-12 07:16:33,831] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 07:16:33,832] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'pkill -9 -f /opt/***/dags/consumer_tweets.py']
[2022-05-12 07:16:33,839] {subprocess.py:85} INFO - Output:
[2022-05-12 07:16:33,841] {subprocess.py:92} INFO - bash: line 1: pkill: command not found
[2022-05-12 07:16:33,842] {subprocess.py:96} INFO - Command exited with return code 127
[2022-05-12 07:16:33,852] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-05-12 07:16:33,859] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stop_live_stream_Dag, task_id=stop_consumer_twitter_data, execution_date=20220512T071633, start_date=20220512T071633, end_date=20220512T071633
[2022-05-12 07:16:33,871] {standard_task_runner.py:97} ERROR - Failed to execute job 7 for task stop_consumer_twitter_data (Bash command failed. The command returned a non-zero exit code 127.; 1475)
[2022-05-12 07:16:33,916] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 07:16:33,936] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
