[2022-05-12 07:39:45,479] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_consumer_twitter_data manual__2022-05-12T07:39:44.969752+00:00 [queued]>
[2022-05-12 07:39:45,490] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_consumer_twitter_data manual__2022-05-12T07:39:44.969752+00:00 [queued]>
[2022-05-12 07:39:45,491] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:39:45,491] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 07:39:45,492] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:39:45,500] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stop_consumer_twitter_data> on 2022-05-12 07:39:44.969752+00:00
[2022-05-12 07:39:45,504] {standard_task_runner.py:52} INFO - Started process 374 to run task
[2022-05-12 07:39:45,507] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stop_live_stream_Dag', 'stop_consumer_twitter_data', 'manual__2022-05-12T07:39:44.969752+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/stop_live_stream_dags.py', '--cfg-path', '/tmp/tmpyavqj0xz', '--error-file', '/tmp/tmpgw8wm9u_']
[2022-05-12 07:39:45,509] {standard_task_runner.py:80} INFO - Job 2: Subtask stop_consumer_twitter_data
[2022-05-12 07:39:45,578] {task_command.py:369} INFO - Running <TaskInstance: stop_live_stream_Dag.stop_consumer_twitter_data manual__2022-05-12T07:39:44.969752+00:00 [running]> on host c5e465c36164
[2022-05-12 07:39:45,681] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=stop_live_stream_Dag
AIRFLOW_CTX_TASK_ID=stop_consumer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T07:39:44.969752+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T07:39:44.969752+00:00
[2022-05-12 07:39:45,685] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 07:39:45,687] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'pkill -9 -f /opt/***/dags/consumer_tweets.py']
[2022-05-12 07:39:45,700] {subprocess.py:85} INFO - Output:
[2022-05-12 07:39:45,722] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 07:39:45,742] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 07:39:45,747] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stop_live_stream_Dag, task_id=stop_consumer_twitter_data, execution_date=20220512T073944, start_date=20220512T073945, end_date=20220512T073945
[2022-05-12 07:39:45,910] {standard_task_runner.py:97} ERROR - Failed to execute job 2 for task stop_consumer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 374)
[2022-05-12 07:39:45,925] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 07:39:46,038] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
